services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=testdb'
      - 'MYSQL_PASSWORD=somepass'
      - 'MYSQL_ROOT_PASSWORD=somepass'
      - 'MYSQL_USER=range'
    ports:
      - '3306:3306'
